import 'package:flutter/material.dart';

/// Two hand-paired palettes: forest green actions, warm paper surfaces, and
/// muted brass for secondary notices. Red stays reserved for errors.
///
/// Contrast pairs are covered by `test/app/theme/theme_contrast_test.dart`.
abstract final class AppColorSchemes {
  static const light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF2E5942),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFD7E5D8),
    onPrimaryContainer: Color(0xFF152F20),
    primaryFixed: Color(0xFFD7E5D8),
    primaryFixedDim: Color(0xFFB6D1B9),
    onPrimaryFixed: Color(0xFF152F20),
    onPrimaryFixedVariant: Color(0xFF3F6B51),
    secondary: Color(0xFF626B61),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFE3E7DF),
    onSecondaryContainer: Color(0xFF1C251D),
    tertiary: Color(0xFF805821),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFF4E4C9),
    onTertiaryContainer: Color(0xFF3E2D18),
    error: Color(0xFFB3261E),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFF9DEDC),
    onErrorContainer: Color(0xFF410E0B),
    surface: Color(0xFFF4F2EA),
    surfaceDim: Color(0xFFE9E7DE),
    surfaceBright: Color(0xFFFFFDF7),
    surfaceContainerLowest: Color(0xFFFFFEFA),
    surfaceContainerLow: Color(0xFFFAF8F1),
    surfaceContainer: Color(0xFFF4F2EA),
    surfaceContainerHigh: Color(0xFFE9E7DE),
    surfaceContainerHighest: Color(0xFFDCDDD2),
    onSurface: Color(0xFF1D261F),
    onSurfaceVariant: Color(0xFF47534A),
    outline: Color(0xFF657267),
    outlineVariant: Color(0xFFC4CBC1),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF2B342D),
    onInverseSurface: Color(0xFFF4F2EA),
    inversePrimary: Color(0xFFB6D1B9),
    surfaceTint: Color(0xFF2E5942),
  );

  static const dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFC1D7C3),
    onPrimary: Color(0xFF183425),
    primaryContainer: Color(0xFF294A35),
    onPrimaryContainer: Color(0xFFE1ECE0),
    // Fixed roles keep the same meaning in both brightness modes.
    primaryFixed: Color(0xFFD7E5D8),
    primaryFixedDim: Color(0xFFB6D1B9),
    onPrimaryFixed: Color(0xFF152F20),
    onPrimaryFixedVariant: Color(0xFF3F6B51),
    secondary: Color(0xFFBFCABE),
    onSecondary: Color(0xFF243026),
    secondaryContainer: Color(0xFF3A493D),
    onSecondaryContainer: Color(0xFFDFE8DE),
    tertiary: Color(0xFFEAC88F),
    onTertiary: Color(0xFF422E12),
    tertiaryContainer: Color(0xFF5C421F),
    onTertiaryContainer: Color(0xFFF4E4C9),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF5A1A15),
    errorContainer: Color(0xFF8C1D18),
    onErrorContainer: Color(0xFFF9DEDC),
    surface: Color(0xFF111813),
    surfaceDim: Color(0xFF111813),
    surfaceBright: Color(0xFF38443B),
    surfaceContainerLowest: Color(0xFF0B110D),
    surfaceContainerLow: Color(0xFF19221B),
    surfaceContainer: Color(0xFF1E2921),
    surfaceContainerHigh: Color(0xFF29362C),
    surfaceContainerHighest: Color(0xFF344238),
    onSurface: Color(0xFFE2E8E0),
    onSurfaceVariant: Color(0xFFC0CCC2),
    outline: Color(0xFF89978B),
    outlineVariant: Color(0xFF4A584D),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFFE2E8E0),
    onInverseSurface: Color(0xFF1D2821),
    inversePrimary: Color(0xFF2E5942),
    surfaceTint: Color(0xFFC1D7C3),
  );
}
